# Laboratorio 4 

## Primer punto

### a)

In [83]:
from matplotlib import pyplot, pylab, mlab
from pylab import *
from scipy.optimize import linprog
import numpy as np
import math 
from math import factorial
from scipy.optimize import minimize
import sympy as sym
from itertools import combinations


In [126]:
def soluciones_basicas (A,b):
    sol_bas = None
    base = None
    columnas = np.size(A[0])
    filas = np.size(b[:,0])
    ans = {"Solucion": sol_bas,
            "Base":base  }
    matrices = list (combinations(np.arange(0, columnas, 1),filas))
    for i in range(len(matrices)):
        sub_A = []
        for j in ((matrices[i])):
                sub_A.append(A[:,j])
        sub_A =  (np.array(sub_A)).transpose()
        #print (np.linalg.solve(sub_A,b))
       
    return  

### b)


In [85]:
#Se crean las matrices  y  vector que determinan el sistema de ecuaciones 
A1 = np.array([[1 ,1,1,1,1 ],[1,2,3,4,5], [4,3,3,3,4]])
A2 = np.array([[1 ,1,1,1,1 ],[1,2,3,4,5], [2,3,4,5,6]])
b = np.array([[1],[2],[3]])

In [127]:
soluciones_basicas(A1,b)


Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current function value: -0.000000   
         Iterations: 0
[0. 0. 0.]
Optimization terminated successfully.
         Current f

In [87]:
com =list (combinations([1,2,3,4,5],3))
len (com[0])

3

### C)


## Segundo Punto

### a)


### b)

### c)